In [ ]:
# Scientific computing package
# NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.
# convert float arrays to int array
# consume less memory than python list
# faster than python lists
# list=[1,2,3,4]
# array=[1 2 3 4] ,no commas
# numpy array store only 1 datatye unlike python list which can store multiple datatypes
# % timeit=>function to check time taken by a function one line
# % % timeit=>function to check time taken by a function multiple lines


In [ ]:
import numpy as np
x=np.array([1,2,3,4,5])
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
lista=[1,2,3,4,5]
print(lista)
print(type(lista))

[1, 2, 3, 4, 5]
<class 'list'>


In [3]:
import numpy as np
arr=np.array([1.2, 2.3, 3.4, 4.5])
integer_arr=arr.astype(int)
print(integer_arr) # Output: [1 2 3 4]

[1 2 3 4]


In [4]:
%timeit integer_arr=arr.astype(int) # 1.2,2.3,3.4,4.5=>1,2,3,4

900 ns ± 138 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [5]:
%timeit [j**4 for j in range (1,9)]#
# list timings=3.1s

3.66 μs ± 816 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [6]:
import numpy as np
%timeit np.arange(1,9)**4 # 1,2,3,4,5,6,7,8=>1,16,81,256,625,1296,2401,4096
# it consumed less timings than list comprehension

3.29 μs ± 565 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [7]:
import numpy as np
l=[]
for i in range(1,5):
    inp=int(input("Enter ur number:"))
    l.append(inp)
x=np.array(l)
print(x)
print(x.ndim) # 1D array
print(x.shape) # 5 elements in 1D array
 

[3 4 1 2]
1
(4,)


In [8]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim) # 2D array
print(arr.shape) # 2 rows and 3 columns(2,3)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [9]:
lis=[[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]]]
print(lis)
%timeit lis

[[[1, 2, 3], [1, 2, 3], [1, 2, 3]], [[1, 2, 3], [1, 2, 3], [1, 2, 3]]]
41.2 ns ± 13.1 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [10]:
import numpy as np
%timeit np.array([[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]]])
print(arr.ndim) # 3D array

5.49 μs ± 995 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
2


In [11]:
# to create 10D array
import numpy as np
arr=np.array([1,2,3,4],ndmin=10)
print(arr)
print(arr.ndim) # 10D array
print(arr.shape) # 1D array with 10 dimensions

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10
(1, 1, 1, 1, 1, 1, 1, 1, 1, 4)


In [12]:
# zeros array
import numpy as np
arr=np.zeros(4)
print(arr)


[0. 0. 0. 0.]


In [13]:
import numpy as np
arr=np.zeros((2,3))
print(arr) # 2 rows and 3 columns with 0 values
print(arr.ndim) # 2D array

[[0. 0. 0.]
 [0. 0. 0.]]
2


In [14]:
import numpy as np
arr=np.ones((2,3))
print(arr) # 2 rows and 3 columns with 0 values
print(arr.ndim) # 2D array

[[1. 1. 1.]
 [1. 1. 1.]]
2


In [15]:
import numpy as np
arr=np.empty((2,3))
print(arr) # 2 rows and 3 columns with 0 values
print(arr.ndim) # 2D array

[[1. 1. 1.]
 [1. 1. 1.]]
2


In [16]:
import numpy as np
arr=np.arange(10)
print(arr) # 2 rows and 3 columns with 0 values
print(arr.ndim) # 2D array

[0 1 2 3 4 5 6 7 8 9]
1


In [17]:
# diaagonal
import numpy as np
arr=np.eye(4,6)
print(arr)
print()
import numpy as np
arr=np.eye(5)
print(arr)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [18]:
import numpy as np
x=np.linspace(0,20,num=5)
print(x)

[ 0.  5. 10. 15. 20.]


In [19]:
import numpy as np
x=np.random.rand(4)
print(x)
print()
x=np.random.choice(4)
print(x)
print()
x=np.random.randint(4,20,5)
print(x)
print()
x=np.random.randn(4)
print(x)
print()
x=np.random.ranf(4)
print(x)

[0.0224274  0.82276222 0.06012473 0.26001013]

2

[19 17 17 13 16]

[ 0.92040273 -1.00200278  0.11082838  0.50065884]

[0.92129872 0.42729691 0.02320263 0.39009896]


In [20]:
# check datatype
import numpy as np
x=np.array([1,2,3,4,5,12,12,3,4,5])
print(x)
print(x.dtype)

[ 1  2  3  4  5 12 12  3  4  5]
int64


In [21]:
# check datatype
import numpy as np
x=np.array(["anu","shy","wer","war"])
print(x)
print(x.dtype)

['anu' 'shy' 'wer' 'war']
<U3


In [22]:
# check datatype, make it float
import numpy as np
x=np.array([1,2,3,4,5,12,12,3,4,5],dtype="f")
new=np.int32(x)
print(x)
print(new)
print(x.dtype)
print(new.dtype)

[ 1.  2.  3.  4.  5. 12. 12.  3.  4.  5.]
[ 1  2  3  4  5 12 12  3  4  5]
float32
int32


In [23]:
# Type conversion
import numpy as np
x=np.array([1,2,3,4,5])
new=x.astype(str)
print(x)
print(new)


[1 2 3 4 5]
['1' '2' '3' '4' '5']


In [24]:
import numpy as np
x=np.array([1,2,3,4,5,6])
y=np.array([19,28,35,43,52,61])
z=np.add(x,y)
print(z)

[20 30 38 47 57 67]


In [25]:
import numpy as np
x=np.array([1,2,3,4,6])
y=x+4
print(x)
print(y)

[1 2 3 4 6]
[ 5  6  7  8 10]


In [26]:
import numpy as np
x=np.array([1,2,3,4,5,6])
y=np.array([19,28,35,43,52,61])
z=np.subtract(x,y)
print(z)

[-18 -26 -32 -39 -47 -55]


In [27]:
import numpy as np
x=np.array([1,2,3,4,5,6])
y=np.array([19,28,35,43,52,61])
z=np.multiply(x,y)
print(z)

[ 19  56 105 172 260 366]


In [28]:
import numpy as np
x=np.array([1,2,3,4,5,6])
y=np.array([19,28,35,43,52,61])
z=np.divide(x,y)
print(z)

[0.05263158 0.07142857 0.08571429 0.09302326 0.09615385 0.09836066]


In [29]:
import numpy as np
x=np.array([1,2,3,4,5,6])
y=np.array([19,28,35,43,52,61])
z=np.mod(x,y)
print(z)

[1 2 3 4 5 6]


In [30]:
import numpy as np
x=np.array([1,2,3,4,5,6])
y=np.array([19,28,35,43,52,61])
z=np.reciprocal(x,y)
print(z)

[1 0 0 0 0 0]


In [31]:
import numpy as np
x=np.array([1,2,3,4,5])
y=np.min(x)
print(x)
print(y)


[1 2 3 4 5]
1


In [32]:
import numpy as np
x=np.array([1,2,3,4,5])
y=np.max(x)
print(x)
print(y)


[1 2 3 4 5]
5


In [33]:
import numpy as np
x=np.array([1,2,3,4,5])
y=np.argmax(x)
print(x)
print(y)


[1 2 3 4 5]
4


In [34]:
import numpy as np
x=np.array([1,2,3,4,5])
y=np.argmin(x)
print(x)
print(y)


[1 2 3 4 5]
0


In [35]:
# axis accessing
import numpy as np
x=np.array([[1,2,3,4],[1,6,7,8]])
print(np.min(x,axis=0))

[1 2 3 4]


In [36]:
import numpy as np
x=np.array([1,2,3,4,5])
y=np.sqrt(x)
print(x)
print(y)


[1 2 3 4 5]
[1.         1.41421356 1.73205081 2.         2.23606798]


In [37]:
import numpy as np
x=np.array([1,2,3,4,5])
y=np.sin(x)
print(x)
print(y)


[1 2 3 4 5]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [38]:
import numpy as np
x=np.array([1,2,3,4,5])
y=np.cos(x)
print(x)
print(y)


[1 2 3 4 5]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [39]:
import numpy as np
x=np.array([1,2,3,4,5])
y=np.tan(x)
print(x)
print(y)


[1 2 3 4 5]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]


In [40]:
import numpy as np
x=np.array([1,2,3,4,5])
y=np.cumsum(x) #cumulative sum
print(x)
print(y)


[1 2 3 4 5]
[ 1  3  6 10 15]


In [41]:
# transform any dimension to any dimension
import numpy as np
x=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21])
print(x.ndim)

y=x.reshape(7,3)
print(y)
print(y.ndim)

1
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]
2


In [42]:
import numpy as np
h11=np.arange(-5, 5, 0.25)
print(h11)

[-5.   -4.75 -4.5  -4.25 -4.   -3.75 -3.5  -3.25 -3.   -2.75 -2.5  -2.25
 -2.   -1.75 -1.5  -1.25 -1.   -0.75 -0.5  -0.25  0.    0.25  0.5   0.75
  1.    1.25  1.5   1.75  2.    2.25  2.5   2.75  3.    3.25  3.5   3.75
  4.    4.25  4.5   4.75]


In [43]:
import numpy as np
a=np.array([1,2,3,4])
print(a.shape)
# b=np.array([1,2,3])=>it leads broadcast error, it means u have to give the same shape of coloumns and dimensions
# it cannot be (1*3) and (3*1), it has to be (1*3) and (1*3)
print(a)

(4,)
[1 2 3 4]


In [44]:
a=np.array([1,2,3])
print(a.shape)
b=np.array([[1],[2],[3],[4]])
print(b.shape)
print(a+b)

(3,)
(4, 1)
[[2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]]


In [45]:
# indexing 
a=np.array([1,2,3,4])
print(a[1])
print(a[-2])
print('''//////////////////////////////////////////////////////////''')
b=np.array([[1,2,3],[1,2,3]])
print(b.ndim)
print(b[0,1])
print('''//////////////////////////////////////////////////////////''')
c=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]],[[19,20,21],[22,23,24]]])
print(c.ndim)
print(c[1,1,2])
print(c)

2
3
//////////////////////////////////////////////////////////
2
2
//////////////////////////////////////////////////////////
3
12
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]]
